### ISSUE TITLE
Ip adress in docker-compose file

### ISSUE THREAD

**Issue by Tiposbingo** [OlivierGaland/CashFactory#18]
Hi, why there are several IP adres like this one ? https://take.ms/j12IZ

**Comment by OlivierGaland** [comment]
Those are static addresses used by the stack, you can change them if you need (but don't forget to also set the correct subnet in "networks" section of docker-compose).

Those have no consequences unless that specific network need to be reachable over your router for the stack, which is not the case.

Indeed it is not standard adresses used for local network, up to you to switch to more standard ones (192.168.x.x 172.16.x.x and 10.x.x.x) but don't use the same subnet as the one defined for your local network.

**Comment by Tiposbingo** [comment]
Thank you for your reply. Now I understand.
