### ISSUE TITLE
Digital Ocean Droplet not active on honeygain despite successful install

### ISSUE THREAD

**Issue by philiporlando** [OlivierGaland/CashFactory#19]
I was able to install CashFactory on a digital ocean droplet without any issues, but it doesn't appear to be actively sharing data with honeygain. 

![image](https://user-images.githubusercontent.com/24445174/161364521-f913016f-dbc8-4915-981a-cd930fc4c12a.png)

![image](https://user-images.githubusercontent.com/24445174/161364477-bd84a389-c4d2-4517-a6c2-caaeb3400bb9.png)

Would you be able to help troubleshoot? Please let me know if I can share any helpful session info. Thank you for creating this project!

**Comment by OlivierGaland** [comment]
Hello,

It is working fine for me, could you have a look at traces on portainer UI ? You should have similar logs as this img if it is working, it may give a hint on what is the issue : 

![image](https://user-images.githubusercontent.com/26048157/162299310-5adab21b-6daf-47f9-9751-15884d09fa1a.png)

**Comment by philiporlando** [comment]
Thanks for the reply. Would you be able to help me launch portainer.io with my Digital Ocean droplet? I'm not sure how to access these logs on my end right now. Thank you.

**Comment by FatGrizzly** [comment]
@philiporlando Honeygain is for Residential ips, you cant run it in Digitalocean.

**Comment by philiporlando** [comment]
> @philiporlando Honeygain is for Residential ips, you cant run it in Digitalocean.

@FatGrizzly, thank you for letting me know. I figured getting this to run on a virtual machine with a fixed monthly expense of $5 was too good to be true!
