### ISSUE TITLE
Runnning Multiple Instances through residential Proxy

### ISSUE THREAD

**Issue by engageub** [OlivierGaland/CashFactory#23]
Hello,

Thank you for this app. Could you please let me know if I can install multiple instances on the same device with different proxies.

Thank you

**Comment by OlivierGaland** [comment]
Hello,

I'm not expert in this case, so I cannot answer technically, I just know that you can define the network you are using (see network section of docker compose).

That said be careful, It may be against the rules of most apps in the stack and considered as abuse, so you may have your account ban and earnings blocked. So I do not recommend that.
