### ISSUE TITLE
Question about VPS

### ISSUE THREAD

**Issue by dimdenGD** [OlivierGaland/CashFactory#38]
Can't you run this on cheap VPS's? What's stopping people from having 50 VPS running with each running this and earning huge amounts per month? genuine question lol, not exactly sure how this works

**Comment by gittrekt** [comment]
Some services ban accounts that use non-residential IPs and most vps cost more than the ones that allow data center IPs earn

**Comment by dimdenGD** [comment]
Regarding cost, you can get vps that can run this program for around 5$ a month and earn more than that.
But i've just read the ToS of every service and apparently only Peer2Profit and Bitping allow non-residential ips to run their apps, so yeah this won't work I guess..
