### ISSUE TITLE
Error with PacketStream

### ISSUE THREAD

**Issue by MC2738012** [OlivierGaland/CashFactory#40]
Hello, for some weird reason, I am having issues with the PacketStream. When I checked the container logs, I see that it's spamming the following:
![image](https://user-images.githubusercontent.com/20744975/210284219-ba5470b7-0240-4f01-ad5d-62788f9cf440.png)
Do you know what's causing this?

**Comment by OlivierGaland** [comment]
Hello,

I checked on mine and no error of this type, is it the psclient or watchtower container ?

First idea I have is maybe you didn't updated .env file to add your CID before launching the stack (see the <CID> keyword that contain a < , you should replace it with your CID (all the text including <>) exposed in the packetstream app dashboard )

![image](https://user-images.githubusercontent.com/26048157/210284815-9caadf49-803f-4d4c-8e82-e4b9f71035c7.png)

If this was the issue, you just need to delete the 2 containers (psclient and watchtower) on portainer interface then run again sudo docker-compose up -d , it will regenerate the missing containers.

Best regards,
Olivier

**Comment by MC2738012** [comment]
Yup, that was the issue. I forgot to put in the PacketStream CID.

Thanks for the help.
