### ISSUE TITLE
Repocket doesn't work with RP_PASSWORD

### ISSUE THREAD

**Issue by adricoin2010** [OlivierGaland/CashFactory#45]
For it to work well, you have to use the **RP_API_KEY** variable and save the Api Key that appears on the page in it.

Extra: for Earnapp you can use `uuidgen | md5sum` and get a nearly unique ID.

**Comment by OlivierGaland** [comment]
Many thanks for your informations, i've created a release using RP_API_KEY instead of RP_PASSWORD.
