### ISSUE TITLE
Unable to register device ID and modified compose file to use fazalfarhan01's lite version

### ISSUE THREAD

**Issue by simon-bd** [OlivierGaland/CashFactory#47]
### Description
I am facing issues while trying to register my device ID in Earnapp. Whenever I attempt to register the device, the Earnapp dashboard displays the following error message: "Error while linking device: The device is not found."

To address this problem, I made modifications to the compose file and opted to use the lite version provided by fazalfarhan01 as a potential solution.

### Expected Behavior
The device ID should be accepted and successfully registered in Earnapp, allowing for proper device linkage and functionality within the application.

### Actual Behavior
Despite providing the device ID as specified in the compose file, the Earnapp dashboard fails to recognize the device, resulting in the error message: "Error while linking device: The device is not found."

As a workaround, I decided to modify the compose file to use the lite version provided by fazalfarhan01, based on similar issues reported by other users in the repository.

```yaml
# Start of Earnapp section (remove this if Earnapp not wanted)
# Variables to define in .env file:
# EARNAPP_DEVICE_ID: Your node ID: sdk-node-<md5sum>
#                    <md5sum> is a 32 char string containing a-z and 0-9 range:
#                      ex: Easy way to generate one: echo "random string" | md5sum
#                          This will print 9f33ffbb8a9dcedb28ea909775a6b0d3 -
#                          In that case, use: sdk-node-9f33ffbb8a9dcedb28ea909775a6b0d3
Earnapp:
  depends_on:
    - Portainer
    - Webserver
  image: fazalfarhan01/earnapp:lite
  volumes:
    - earnapp-data:/etc/earnapp
  restart: always
  environment:
    - EARNAPP_UUID=$EARNAPP_DEVICE_ID
  networks:
    default:
      ipv4_address: 172.106.0.20
# End of Earnapp section

**Comment by OlivierGaland** [comment]
Missed this one, earnapp:lite was added in a docker-compose some times ago
