### ISSUE TITLE
`peer2profit/peer2profit_x86_64:latest` docker image doesn't exist anymore

### ISSUE THREAD

**Issue by lyenliang** [OlivierGaland/CashFactory#48]
Recently, I want to start my CashFactory in another new computer. But when I run `docker-compose up -d`, I got `Error response from daemon: pull access denied for peer2profit/peer2profit_x86_64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied` error. 

I then checked `https://hub.docker.com/search?q=peer2profit`, and I found that this image doesn't exist anymore.

So I copied `peer2profit/peer2profit_x86_64:latest` image in my old computer to [lyenliang/peer2profit_x86_64](https://hub.docker.com/r/lyenliang/peer2profit_x86_64). This solves the problem.

**Comment by OlivierGaland** [comment]
Hello,

Thanks for noticing this issue, I published a version including the link to your file.

Olivier.
