### ISSUE TITLE
traffmonetizer new pull code for new version

### ISSUE THREAD

**Issue by RocketDevil** [OlivierGaland/CashFactory#50]
Hey @OlivierGaland 

traffmonetizer got a new pull line, could u change the code to it please :)

traffmonetizer/cli_v2:latest

ty

**Comment by OlivierGaland** [comment]
Hello,

Thanks for the informations : I've created release 1.6 that include this change.

Olivier

**Comment by RocketDevil** [comment]
yeah idk why they change there pull code, it's silly to do, or they wanted to create a "funny" inconvenience for ppl who run whole server farms with it :D

but thanks for the fast change of code :)
