### ISSUE TITLE
Proxyrack not starting

### ISSUE THREAD

**Issue by RocketDevil** [OlivierGaland/CashFactory#53]
I totally forgot that my proxyrack shows (screenshot) and there is no option in the CF files to set the #uuid into (I guess next line to the api-key it should be going??)

![grafik](https://github.com/OlivierGaland/CashFactory/assets/64044738/aee12df2-58ab-4dcd-9d88-bab5ceb20242)

**Comment by RocketDevil** [comment]
I mean in the official documentation its in some use too, so I guess its needed in CF somewhere too to be able to let the docker communicate with there system how they write it in there documentation instructions xD

![grafik](https://github.com/OlivierGaland/CashFactory/assets/64044738/fca1b657-3e1c-4c63-8cba-b37ed338d4ae)

**Comment by Xav-Deb** [comment]
I just generate uuid as mentioned in doc and Add it to env variables. It works for me

**Comment by OlivierGaland** [comment]
Hello,

Many thanks for the informations, I will have a try and upgrade cashfactory accordingly.

Regards,
Olivier

**Comment by OlivierGaland** [comment]
v1.8 has been released and should solve the issue.
