### ISSUE TITLE
Add earn.fm and cloudcollab to docker stack

### ISSUE THREAD

**Issue by Xav-Deb** [OlivierGaland/CashFactory#54]
Hi,
I've find 2 other applications dockerizable : 

- https://earn.fm/en/download
- https://cloudcollab.uk/service.html

Could you take a look at these to add to your project?

Thanks

**Comment by OlivierGaland** [comment]
Hello,

Thanks for proposing those application, I'm currently evaluating them and I will add them in the project. So far they are running, I had some tuning to do as earn.fm use watchtower (like packetstream) and we need to use a trick to allow several instance to run on the same docker host, but it seems to work.

If everything is fine I will try to push a new release before end of week.

Olivier

**Comment by CristianT** [comment]
earn.fm seems good and easy to integrate, just an env var.

Don't waste your time with cloudcollab, it doesn't work properly, the docker creates a new id every run, you probably needs to mount some files but there is 0 documentation.

**Comment by OlivierGaland** [comment]
Hello,

I've just commited release v1.9 with EarnFm , I'm still evaluating cloudcollab but got no income for 10 days. I will add it to the stack If I find a way to sort it out.
